### PR TITLE
fix for #29

### PR DESCRIPTION
**Pull request by frank-baier**

### CODE REVIEW

**Comment by frank-baier** [comment]
@matthewwardle Hi Matt, would be happy having you as reviewer on this change.

**Comment by frank-baier** [comment]
@matthewwardle  please hold on a second with reviewing, I need to add the eventId to uploadDocument as well.

**Comment by matthewwardle** [comment]
Hey @frank-baier Looks fine 👍

**Comment by frank-baier** [comment]
Hi @matthewwardle would you mind approving the changes? Please see tab files changed on the top right. This would allow me to merge the changes to master and proceed with issue 31 - addid the callerName

**Pull request merged**
