### PR TITLE
fix for #30, added X-Caller-Name

### PR DESCRIPTION
**Pull request by frank-baier**

### CODE REVIEW

**Comment by frank-baier** [comment]
Hi @matthewwardle happy to have you as reviewer on the caller name issue as well. Could you please approve after review?

**Comment by matthewwardle** [comment]
@frank-baier so what would our called name be? 

Would this not be determined from the API key?  Or is it better to seperate it from that?

**Comment by frank-baier** [comment]
Hi @matthewwardle - a proposal would be that your call name would be "KASKO", while we don't care about case. The goal of the X-Caller-Name header param is to identify uniquely the caller organization. So in our case KASKO should be specific enough.

**Comment by matthewwardle** [comment]
Ah okay.  No problem

**Pull request merged**
